### ISSUE TITLE
After update to Shelly HomeKit 2.11.0, Plug S no reconnect after Wi-Fi night shut off

### ISSUE THREAD

**Issue by chronowerx42** [mongoose-os-apps/shelly-homekit#1018]
Hello there,

now after updating to 2.11.0, the second night all the 16 Plug S devices with mongoose didn't reconnect to Wi-Fi after Wi-Fi night shut off. There is still a test unit running the original Shelly OS that still works fine. I never had such a problem with the previous version. The problem: I'm traveling and can't access anything. Right now I can't tell if a power interruption will bring it back online.

Edit: Two days later, I can confirm all 16 Plug S don't reconnect. First morning some of them still do but the second day all of them are offline again. At least every second day I have to do a power interruption to every single device.

**Comment by Podlipny** [comment]
I have same problem with Shelly1

**Comment by rojer** [comment]
thanks for reporting. indeed, there was a small memory leak in wifi reconnect code that, after long time of trying to connect to wifi, can exhaust device's memory and make it unable to connect again until rebooted.
the bug was fixed in https://github.com/mongoose-os-libs/wifi/commit/cb995cd5e33d107782722ffd5c7b00cd0a4c9f23 and i will push 2.11.1 to deploy the fix.

**Comment by rojer** [comment]
2.11.1 has been released
