### ISSUE TITLE
Shelly uni

### ISSUE THREAD

**Issue by 999delights** [mongoose-os-apps/shelly-homekit#1050]
When the switch 1 input mode is set to detached, and the input type is set as "Doorbell", device is not recognised by the HomeKit .. appears in the app as doorbell indeed But with No use

**Comment by rionshin** [comment]
What are you explaining is not a possible combination - Stateless switch is in the same menu as Doorbell , you cannot have both selected at same time . 
Detached is possible value only for Switch , switch is the type - value is detached . Doorbell is type not value. 
what is your device , can you provide screenshot 
![C0228998-4779-49F9-862C-B62D1858F047](https://user-images.githubusercontent.com/41396180/182480119-90e0c826-68d7-4101-8180-37264ff6c5f7.png)

**Comment by 999delights** [comment]
Thanks, 
Andrei Giangu

**Comment by 999delights** [comment]
Dont want to have Both selected lol ,  just the Doorbell 

But it s not working. Device is not recognised, 
Andrei Giangu

**Comment by markirb** [comment]
It does work this is only a display issue, as it expects a linked camera see e.g.:

https://nrchkb.github.io/wiki/service/doorbell/

Note : An icon with the mention unmanaged appears in the home app. This is due to the fact that a linked service must be added. For example, you can add a light or a camera.
