### ISSUE TITLE
Revert Shelly 1 PM causing unusable state

### ISSUE THREAD

**Issue by tasb** [mongoose-os-apps/shelly-homekit#1203]
I flashed a Shelly 1 PM with success but when I tried to revert the firmware using OTA, everything seems to work properly but I've lost access to my Shelly.
Then I made a factory reset (using Shelly button) and now I get this when connecting directly using http://192.168.33.1

![image](https://user-images.githubusercontent.com/415105/214366541-bebe0b74-73ac-4925-8c74-da3026a929b9.png)

I also tried to revert using python script but I after process runs I stays blocked saying is waiting for reboot, like you can se on below image.

![image](https://user-images.githubusercontent.com/415105/214366789-2036ee8e-52ec-4baa-981a-bc57f80f6593.png)

Any idea how I can really revert to stock firmware?

**Comment by andyblac** [comment]
you can't revert when it is not connected to your network, as it need internet access, rejoin it to your network and try again.

**Comment by fishd72** [comment]
Can confirm I'm seeing this same issue with a Shelly+ 1PM... to recover from this state, you can actually use the install method to put the HomeKit firmware back on, and the settings appear to be retained but it just won't revert to stock firmware via the UI. I don't recall having this issue with the Shelly1 I tried about 3 weeks ago, I'm 99% sure that reverted to stock without issue.

@andyblac the device is actually connected to the network (hence being able to access it via a webpage and receive the "Connecting to Shelly and loading data..." message) but the loader doesn't appear to think so... so not sure what the issue is.

**Comment by MBarti** [comment]
Same problem here. No way to revert to stock firmware on Shelly Plus 1. Stuck on "connecting to Shelly and loading data..."
