### ISSUE TITLE
Shelly 1 vs Shelly 1 Plus

### ISSUE THREAD

**Issue by tamasharasztosi** [mongoose-os-apps/shelly-homekit#1215]
I would like to buy a lot of Shelly devices into newly built house behind wall pushbuttons (stateless) and the first thing will be to flash HomeKit firmware to them.
In this case did anyone tested the two device ping and switching delay, status update delay?
Should I buy the ESP32 version and pay more or not?

**Comment by timoschilling** [comment]
Sorry, we don't support questions which are not related to the firmware here, that's why I will close it.
(Source you want to flash it with our firmware, but what shelly is the same as on stock)

From my point of view the Plus models are switching faster then the old once. If you push a wall switch with an old one, you hear two clicks one from the switch and a bit later the one from the shelly. With the plus models you hear it as one click.
