### ISSUE TITLE
Shelly 2.5 Shutter touch down position

### ISSUE THREAD

**Issue by Patr-ick** [mongoose-os-apps/shelly-homekit#1253]
Something that still holds me back from moving from https://github.com/onfoot/homebridge-shelly-shutter to the Shelly OTA Homekit Firmware is a missing setting for the touch down position.

What it does is literally that I could define what in my personal perspective means "closed". I usually don't want my roller shutters to fully close, I like when they just slightly touch the ground but the individual slats are not closed.

The advantage of this is, I could voice control siri to close my roller shutters and she will move the blinds to the certain set touch down point (and Home App will also display them as "closed"). Without this, Siri always fully closes them until the motor stops. So it is some sort of "offset" from the seconds that are needed for fully closing or fully opening.

Would love to see such feature also for this Firmware.

**Comment by timoschilling** [comment]
Who do you really close the shutter when it’s already closed in Home?

What you want didn’t work with our firmware, we didn’t go by time when closing the window cover, we are going by power consumption. Otherwise we will never know that the cover is really closed. 

For your case use a seen, set covers to 99% or what you want and tell Siri the name of the scene.
