### ISSUE TITLE
new homekit architecture 2023 iOS 16.4

### ISSUE THREAD

**Issue by s-mautone91** [mongoose-os-apps/shelly-homekit#1270]
you can upgrade homekit to the new architecture released with ios 16.4. or could there be problems?

**Comment by timoschilling** [comment]
I use them since half a year, since it was short possible with 16.2, without any problem. The change is only about HomeKit works internally, the behavior how devices get the latest status is different, sometimes better, sometimes worser. The API between HomeKit and accessories didn’t changed so it should work and if not it’s up to HomeKit to fix it.
