### ISSUE TITLE
HomeKit over Thread

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#272]
As the HomePod mini will support this, is this something that can be added to this firmware, as it might help people that are using mesh networks.

https://www.threadgroup.org/What-is-Thread/Thread-Benefits

**Comment by rojer** [comment]
it's a long way off as there's currently no support for Thread in mos.

**Comment by andyblac** [comment]
> it's a long way off as there's currently no support for Thread in mos.

ok, i'll leave ticket open, for future reference.

**Comment by NotClear** [comment]
Theoretically thread runs on the ESP8266, there is no hardware limitation. However, the thread requires an IEEE 802.15.4 radio which the ESP does not have, so it would need to be upgraded.

The Openthread software is already available for the ESP32 but theoretically it would run on the ESP8266 so it only needs a migration of the software.

https://github.com/openthread/ot-esp32

**Comment by MBarti** [comment]
Thread is incredible. It solves all the problems of Zigbee and works extremely well, according to tests and my own experience (With Nanoleaf A19 bulbs). Players like Nanoleaf and Eve Systems will move to 100% Thread and everyone else will follow. The open source libraries are there for the taking.
 
It's becoming clear that EVERY major producer will move to Thread within a few years, because it solves all the problems with Zigbee and all the Big Boys support it, as a spiritual successor to Zigbee, which lacked interoperability and required bridges. 
Since Homepod Mini seems to be a big hit, the demand is there. 

Thread itself supporters: (+Apple)
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/22871912/110682812-aa4e2100-81db-11eb-9d72-492331e6740d.png">

CHIP project supporters (Thread will be one of the main networking layers, NOT Zigbee):
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/22871912/110683192-0ca72180-81dc-11eb-8093-941ee790d687.png">

**Comment by timoschilling** [comment]
@rojer and @andyblac what do you think? I think this thread can be closed for multiple reasons:
1. Thread can't run on the current Shelly hardware, so the request is out of scope for this project
2. If a future hardware would be possible to run Thread aka supports IEEE 802.15.4, I would expect Shelly would already support Thread out of the box

For me this request is a feature request to run this firmware on devices which aren't exist right now, like I would request for camera support and Shelly didn't have a camera product. (I know they had one in the past, it's just an example)

**Comment by andyblac** [comment]
fine by me.

**Comment by rojer** [comment]
yes, closing

**Comment by gmuth** [comment]
I think with Gen4 the hardware (ESP-Shelly-C68F) now supports OpenThread:
https://docs.espressif.com/projects/esp-idf/en/stable/esp32c6/api-guides/openthread.html
Could you reevaluate possible solutions?

**Comment by markirb** [comment]
It should be possible in general, and I would find this quite nice personally. 


But is it also feasible for this firmware? I guess not really. 
The first problem is that we have no support yet for gen4 which yet another chip. And as mongoose is is basically dead we do not expect an update for the precompiled ota library, which is the very base for this firmware...

Similar with thread. I see that espressif has some thread library and examples. But porting this and then have matter support over thread.... I would love to contribute to something like that but doing it on my own is not possible at all currently.

**Comment by gmuth** [comment]
OK, I am not that familiar with the origins of the project.
I guess even just OpenThread without Matter support would be hard to get working.

- What are the main features of the precompiled ota library? TCP/IP an HTTP?
- Is Wifi included in the library?
- I guess for flashing the code is available or should not impose a major issue.
- Why is precompiled important? If the source is available a binary could be build.
- Isn't "the library" the new focus for cesanta? https://github.com/cesanta/mongoose
