### ISSUE TITLE
Temperature Shelly 2.5 very hot

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#333]
Hi my shelly2.5 are very hot, is it normal?
![FD2DB2B8-AC09-40EB-9D4A-80917489D85A](https://user-images.githubusercontent.com/74553551/101998698-eb669000-3cd5-11eb-8d8c-9280ef7304cf.jpeg)
![7179226C-8A79-4E6E-8524-B9D7DB8092A6](https://user-images.githubusercontent.com/74553551/101998700-ed305380-3cd5-11eb-8cf9-cc7fe4db1b10.jpeg)
![4D5D4359-FA33-4684-872A-B4A31ADE2127](https://user-images.githubusercontent.com/74553551/101998701-edc8ea00-3cd5-11eb-80aa-fbdb4fc246fc.jpeg)
Re ad this:
https://github.com/arendst/Tasmota/issues/7991
And this:
https://savjee.be/2020/11/shelly25-esphome-potential-fire-hazard-fix/?fbclid=IwAR30ZrNEQD27HYNRr8j3UWdjSdV7l4_J7JXXhfaQ4X8SpcoePUNy5mmzamg

**Comment by rojer** [comment]
in upcoming 2.7 release an updated NTC conversion curve is used - please try 2.7.0 pre release and let me know - https://github.com/mongoose-os-apps/shelly-homekit/issues/330

you should see lower temperature readings

**Comment by rojer** [comment]
arendst/Tasmota#7991 > Due to the gpio init change the IRQ gpio was never correctly initialized resulting in an output signal from the esp8266 which would be shorted to gnd by any ade irq resulting in heat and possibly hardware failure over time.

does not apply to this firmware, we don't use gpio16 so it remains configured as an input (default reset state).
