### ISSUE TITLE
max number of connections

### ISSUE THREAD

**Issue by christi-g** [mongoose-os-apps/shelly-homekit#422]
Hello, currently the maximum number of connections is limited to 9. 
Is it possible that more connections are possible? I have already reached the maximum number...

<img width="531" alt="shelly-homekit" src="https://user-images.githubusercontent.com/77681634/105359173-6edda000-5bf7-11eb-8622-98c5ef64f159.png">

Thanks

**Comment by andyblac** [comment]
i'm currently testing a version tht better handles the connections, dropping ones that are no used for a set period, so far seem to be working better. I'll keep you updated.

**Comment by andyblac** [comment]
new upcoming version, they have been increased to 12 max connections, and better still old ilde connections get dropped, as they become stale.

**Comment by rojer** [comment]
released in 2.7.3

**Comment by christi-g** [comment]
Thx ☺️

**Comment by simonfield76** [comment]
Andy sorry for the question but could you give us more details about the old connections? After how long does the device will become stale?

During summer I usually return home every 7/9 days i don’t want arriving home and nothing works with my phone because I’ve been out.

In next release could you put an option to automatically cancel old connection if not used?

Inviato da iPhone

Il giorno 24 gen 2021, alle ore 12:23, Andy Blackburn <notifications@github.com> ha scritto:

﻿

new upcoming version, they have been increased to 12 max connections, and better still old ilde connections get dropped, as they become stale.

**Comment by rojer** [comment]
@simonfield76 Andy was not quite correct in his description of the behavior.
in fact, we do not actively drop connections if there is no slot shortage, connections will stay open indefinitely.
but if we are at limit (used to be 9, now 12) and a new connection comes in, we will find the connection that has been idle the most time (time since last request) and evict it to make room for the new one.

**Comment by timoschilling** [comment]
And dropping the connection even doesn’t mean unpairing. It only means that your 13. device isn’t connected and only controls the device indirectly through an other iOS device

**Comment by rojer** [comment]
correct. this is about dropping a TCP connection, not pairing associaction.

**Comment by andyblac** [comment]
Sorry for the confusion.

**Comment by simonfield76** [comment]
Thank you very much for the clarification!!!

Your work is very much appreciated!!!

Inviato da iPhone

Il giorno 24 gen 2021, alle ore 18:18, Andy Blackburn <notifications@github.com> ha scritto:

﻿

Sorry for the confusion.
