### ISSUE TITLE
homekit location based automation do not work

### ISSUE THREAD

**Issue by ari-ido-999** [mongoose-os-apps/shelly-homekit#432]
Hello,

I tried a few scenarios where I leave/arrive home and none of them seem to to turn on/off the shelly 1 switches I have.  I have a homepod mini and all the locations settings seem correct. Are these supposed to work?

**Comment by andyblac** [comment]
works here np, anyway this is HomeKit issue not of thise Firmware.

**Comment by ari-ido-999** [comment]
Thanks, any idea to figure out where is the problem?

**Comment by andyblac** [comment]
do you only have a single hub ?

**Comment by andyblac** [comment]
do you location enabled in HomeKit in yours system settings ? (settings icon in main iOS)

**Comment by ari-ido-999** [comment]
yes of course , all the settings that appear here are configured correctly https://techtechandmoretech.com/guides/how-to-fix-homekit-location-automation/
    On Monday, January 25, 2021, 03:21:40 PM GMT+2, Andy Blackburn <notifications@github.com> wrote:  
 
 


do you location enabled in HomeKit in your system settings ? (settings icon in main iOS)

**Comment by andyblac** [comment]
no AppleTV's if you do, disable HomeKit on them, they can cause issue with automations and HomeKit.

**Comment by ari-ido-999** [comment]
I use homepod mini 
    On Monday, January 25, 2021, 03:28:32 PM GMT+2, Andy Blackburn <notifications@github.com> wrote:  
 
 


no AppleTV's if you do, disable HomeKit on them, they can cause issue with automations and HomeKit.

**Comment by andyblac** [comment]
it should work then, can you post some screenshots of your workflow ?,

**Comment by ari-ido-999** [comment]
This automation for example is supposed to turn off the shelly 1 but it doesn't. Is it supposed to be immediate or can take time. I waited for about 10 minutes 100 meters from my home. 



Sent from Yahoo Mail for iPhone


On Monday, January 25, 2021, 3:39 PM, Andy Blackburn <notifications@github.com> wrote:




it should work then, can you post some screenshots of your workflow ?,

**Comment by Whiterabbit64** [comment]
> This automation for example is supposed to turn off the shelly 1 but it doesn't. Is it supposed to be immediate or can take time. I waited for about 10 minutes 100 meters from my home.  Sent from Yahoo Mail for iPhone On Monday, January 25, 2021, 3:39 PM, Andy Blackburn <notifications@github.com> wrote: it should work then, can you post some screenshots of your workflow ?, — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I think 100m is not enough. Location works with a radius of 300 or 400m. You can’t set less than that.

**Comment by andyblac** [comment]
> > This automation for example is supposed to turn off the shelly 1 but it doesn't. Is it supposed to be immediate or can take time. I waited for about 10 minutes 100 meters from my home.  Sent from Yahoo Mail for iPhone On Monday, January 25, 2021, 3:39 PM, Andy Blackburn [notifications@github.com](mailto:notifications@github.com) wrote: it should work then, can you post some screenshots of your workflow ?, — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> I think 100m is not enough. Location works with a radius of 300 or 400m. You can’t set less than that.

yeah IIRC the HomeKit specs are a Minimum of 200m is required, but the more distance assures better activation of automation iirc @Whiterabbit64 is correct 300m+ is recomended.

**Comment by simonfield76** [comment]
I have disabled the function away/back to home to my gate for the same reason. Whenever I go out with my dog for his walk it take action too far on my way back and returning from job the distance is too short to keep the door open.  Moreover due to the fact that it is configured as garage door it needs an extra confirmation by logging into the phone.

Same happened with my old gate Bluetooth opener Solo.

Inviato da iPhone

Il giorno 25 gen 2021, alle ore 17:57, Andy Blackburn <notifications@github.com> ha scritto:

﻿

This automation for example is supposed to turn off the shelly 1 but it doesn't. Is it supposed to be immediate or can take time. I waited for about 10 minutes 100 meters from my home.  Sent from Yahoo Mail for iPhone On Monday, January 25, 2021, 3:39 PM, Andy Blackburn notifications@github.com<mailto:notifications@github.com> wrote: it should work then, can you post some screenshots of your workflow ?, — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I think 100m is not enough. Location works with a radius of 300 or 400m. You can’t set less than that.

yeah IIRC the HomeKit specs are a Minimum of 200m is required, but the more distance assures better activation of automation iirc @Whiterabbit64<https://github.com/Whiterabbit64> is correct 300m+ is recomended.

**Comment by andyblac** [comment]
so, can i close issue ?

**Comment by ari-ido-999** [comment]
Yes, it works with my son's phone so it is something else not your software
