### ISSUE TITLE
2x Shelly 1: HomeKit Automations not working

### ISSUE THREAD

**Issue by felixmueller** [mongoose-os-apps/shelly-homekit#47]
Hi there,

I installed multiple Shelly 1’s in my home, primarily to use them for automations.

For instance: when Shelly A is switched off, switch off Shelly B as well. 

Unfortunately, this does not work at all. When I create a new „When an accessory is controlled“ automation for Shelly A (disable) then disable Shelly B, nothing happens. 

Maybe it is kind of a timing issue, it is possible to trigger a smart bulb when switching a Shelly, but not another Shelly. 

Did someone experience the same issue and is there any solution for this?

Thanks a lot!

**Comment by andyblac** [comment]
works here, what are you using as a HomeKit Hub ?

**Comment by felixmueller** [comment]
I have an Apple TV and a HomePod in my network. The ATV is always the active Hub.

**Comment by andyblac** [comment]
I had issue with ATV as hub, trying disabling as a Hub in gui.

**Comment by felixmueller** [comment]
I just disabled the Home Hub feature on my ATV and the HomePod took over. And after disabling and re-enabling the Automations it now works!

Thank you very much @andyblac !

I do not understand why this is still an issue and Apple didn’t fix it yet.

**Comment by andyblac** [comment]
yeah, but thats Apple for you.

**Comment by qx54** [comment]
I have an Apple TV as hub and Lifx bulbs. I'm about to buy Shelly 1's and 2.5's.

@andyblac & @felixmueller, are you saying that shelly-homekit won't work with my Apple TV as hub?

**Comment by felixmueller** [comment]
Hi @qx54

I switched from this firmware do the homebridge-shelly plugin. 

Since then, I had no more issues with automations. 

The problems I had were not caused by my Apple TV. The Shelly firmware was not operating reliably.

**Comment by qx54** [comment]
Hi @felixmueller 

Thanks for your feedback. I'm considering Homebridge now.

**Comment by felixmueller** [comment]
@qx54 

I don't want to blame the firmware for my issues. I think its awesome software. 

It just didn't work out in my case. Maybe it was the WiFi or something else.

The Homebridge plugin however worked very reliably from day one.

**Comment by rojer** [comment]
bugs happen, we need to figure this out. #178 is probably the same issue.

**Comment by qx54** [comment]
I'm aware of this and from browsing a couple of issues related to my interests (e.g. single, double, long press) I can tell you're very active and doing a tremendous job!

But because I already have Sonos devices which by default don't integrate well with homekit, this might just be the push I needed to buy a Raspberry and install homebridge. So it's more about Sonos and not so much about this issue ;)

**Comment by andyblac** [comment]
For me I find homebridge way less reliable than this firmware. I have no issues with firmware

My automations issues are down to the HomePod as it effects all my HomeKit devices

I personally would recommend this firmware over homebridge.

**Comment by Rappelsack** [comment]
I guess this thread is now the active one? 

I wrote my issues already here: https://github.com/mongoose-os-apps/shelly-homekit/issues/178

So my next step was:
shut off the Homepod (so that only my iPad is active and the hub). Switching all automations to deactivate and activate again. Restart iPad.
And: the shutter (only this one who is displayed as a bridge) still is down even it should go up at 06:30 am this morning.
And all Shelly 1 (floor heating) stayed off this morning.

So I did the same troubleshooting but now with the Homepod as active hub:
same problems. 

Therefore I suggest that it must be the firmware of the shellys? It worked finde all the way to 2.1.8.
