### ISSUE TITLE
Tilt Angle for Window Covering

### ISSUE THREAD

**Issue by oliverrahner** [mongoose-os-apps/shelly-homekit#560]
Hi,

I'm thinking about getting a Shelly 2.5 for an office where we have outside window coverings like these:

![image](https://user-images.githubusercontent.com/2277681/110923656-69f8bb00-8321-11eb-9776-5a7d3165d344.png)

I now want to use the HAP feature Horizontal Tilt Angle to control the slat angle, but I couldn't find support for this in the source code. Did I miss something? If not, is it planned to support this scenario?

**Comment by timoschilling** [comment]
How is it controlled? What kind of wiring is needed for it?
I would expect a 4 wire setup:
1. window cover down
2. window cover up
3. tilt angle increase
4. tilt angle decrease

If it's like that you can't use a 2.5, you would need a 4 channel devices, which didn't exist.

**Comment by oliverrahner** [comment]
No, it's mechanically coupled.
When the motor starts turning in the "down" direction, first the slats are rotated to fully closed, then the down motion begins.
When the motor starts turning in the "up" direction, first the slats are rotated to fully opened, then the up motion begins.

The Fibaro Roller Shutter supports this, for example:
https://manuals.fibaro.com/content/manuals/en/FGR-223/FGR-223-EN-T-v1.2.pdf
see page 11: "Slats positioning in venetian blinds mode"

If needed, I can provide a video showing the function in real life.

**Comment by zsolt-dev** [comment]
Something like this is a much needed feature, but not sure if possible.

There could be a parameter, something like this:

// how much time in miliseconds to tilt the cover slates
timeToTilt: 250
After that it would expose a new button called tilt.

But not sure how to implement the tilt sequence in homekit (fully close blinds and then press button)

**Comment by timoschilling** [comment]
The Problem what I see is that you can create a state from the home app which your cover can't achieve.
You can say in HK the cover is 50% and the title angle is 50% closed, that something your WC can't do. It can only have close 0%-99% close / tilt 0% or 100% closed / 0%-100% tilt. Because in your planed setup you only can change on parameter at a time, but HK allows both.

**Comment by oliverrahner** [comment]
I actually started implementing this, but am not currently working on it anymore. I think it would be perfectly possible.
First, you can tell Homekit if your cover is capable of (vertical) tilting, and also by how much.
But even if we don't want to do that, because of the added configuration needed to be done, 100% can just mean exactly that: fully tilted. 0% can mean "no tilted" or "tilted in the other direction".

"timeToTilt" or something like that would be the only required configuration, assuming it takes the same amount of time in both directions to reach the extreme positions.

We receive a command like "50% open, 30% tilt" from Homekit. Say we are coming from "0% open, 100% tilt".
We would then start the motion in the up direction for timeToTilt (to reach 100% -> 0% tilt) + 50%*move_time_ms. Then, we start the motion in the down direction for 30% of timeToTilt. The needed logic wouldn't be too complex, but involves some thinking (or trial-and-erroring :)).

**Comment by timoschilling** [comment]
If I understand you right you want to fix that problem that you can’t change the angle while the WC isn’t fully closed by telling HK that the angle has a min and max of for example 0, is that right?

If that’s your workaround, you have the problem that you can’t change that min/max value at runtime. You can only set it on boot time of the HK Server. So yes in theory your plan can work, in practice not.

**Comment by oliverrahner** [comment]
Sorry I don't understand what problem you see there. Maybe I didn't describe the way the covering works precisely enough?

**Comment by timoschilling** [comment]
> You can physically reach any combination of opening and tilting levels.

ok, then never mind, I have misunderstood you

**Comment by zsolt-dev** [comment]
> We receive a command like "50% open, 30% tilt" from Homekit. Say we are coming from "0% open, 100% tilt".
> We would then start the motion in the up direction for timeToTilt (to reach 100% -> 0% tilt) + 50%*move_time_ms. Then, we start the motion in the down direction for 30% of timeToTilt. The needed logic wouldn't be too complex, but involves some thinking (or trial-and-erroring :)).

This sounds amazing. If this would possible it would be great. But not sure if HK support the tilt feature. If this solution is not possible I would at least like to have some "dumb" solution, like exposing extra HK button that would just run the motor up for the specified timeToTilt. I would set it to the time it takes for the slates to be in my most commonly used position.

**Comment by oliverrahner** [comment]
Homekit does support it. Even in two separate flavors of horizontal and vertical tilt.
It's not implemented very beautifully in the UI, but it is there:
![image](https://user-images.githubusercontent.com/2277681/114532050-bc910400-9c4c-11eb-9086-6d5b4e6d4a50.png)

**Comment by zsolt-dev** [comment]
@oliverrahner Thats great news! Your proposed solution is the way to go then.

Is there anyone here who knows c++ and would like to implement it? If there was a crowdsourcing for this I would even pay something.

**Comment by brancooo1** [comment]
That would be much appreciated feature. I know in many countries are usual blinds without tilt, but in multiple countries it’s the only standard solution. All models I know work exactly the proposed way and the implementation would be awesome.

**Comment by timoschilling** [comment]
It may be a good request But I think it’s something that must be implemented by someone how has this kind of window covers. So if some would like to implement it, PRs are welcome.

**Comment by oliverrahner** [comment]
I already started this but got sidetracked 😄 maybe I can share the work in progress in a PR in the next days

**Comment by stresli** [comment]
> I already started this but got sidetracked 😄 maybe I can share the work in progress in a PR in the next days

that would be nice to share.

**Comment by oliverrahner** [comment]
PR #707 includes my current working progress

**Comment by simonproebstl** [comment]
Is there any news here?

**Comment by oliverrahner** [comment]
I watched my own blinds a bit more and saw that my previous analysis wasn't 100% accurate:

> When the motor starts turning in the "down" direction, first the slats are rotated to fully closed, then the down motion begins.
> When the motor starts turning in the "up" direction, first the slats are rotated to fully opened, then the up motion begins.

The slats are, in both cases, rotating **while** the up/down motion is already in progress.
This complicates the calculation a bit, but it should be handable.

@brancooo1 can you confirm that your blinds behave the same way?

**Comment by WatsonDue2** [comment]
Hi,
my blinds works exactly the same way.

When the motor starts turning in the "down" direction, first the slats are rotated to fully closed, then the down motion begins.
When the motor starts turning in the "up" direction, first the slats are rotated to fully opened, then the up motion begins.


So, slats are moving (tilting) first when I press up/down. When they are fully open/close, the blind starts going up/down.

This happens at any height of the blind.


Just like this video, but with an electrical motor :D
https://www.youtube.com/watch?v=eXACkwB8ZRI

**Comment by zsolt-dev** [comment]
@oliverrahner 

Just played with mine today and you are right, they are rotating **while** moving. I have never noticed it before, you have to look for it to test it.

@WatsonDue2 In the provided video (with the manual blinds) you can tilt the blinds the other way around. With electric (at least mine) you can tilt it only one way... I have never seen motor blinds that would work like the one on the video.

How mine work:
1. When they go down, they tilt to the closed position
2. When they go up, they tilt to open

**Comment by kodi83** [comment]
Hi,

just found this issue and the current perperations made by @oliverrahner. 

I took his code and updated the codebase to 2.11.1. While implementing the movement logic, I ran into a couple of questions:
- My blinds behave like them, @WatsonDue2 posted in the video. But just motor-driven. If I am interpreting the description of @zsolt-dev correctly, you have just closed (vertically alignment of the blinds while moving down) and open (horizontal alignment of the blinds when moving up) as endposition when moving your blinds up and down. If I would like to have my blinds transparent, I need to adjust the tilt to 50% (90 degree, because I have 0 and 180 degree as endpoints). 
- Is the reset of the tilt necessary after moving of the blinds? We use them just closed (with tilting) or fully open. I assume, if you close the blind you do not want to tilt to the transparent mode. Right?

The tilting logic is implemented the following:
1. You need to configure a slat movement time. This is to be measured manually and describes the time, tilting needs from endposition to endposition. If this setting is 0, the feature is described.
![Bildschirmfoto 2022-07-11 um 15 02 00](https://user-images.githubusercontent.com/48414034/178272008-65767b6a-5626-4b4d-ac96-9ea2bf82b710.png)
3. When moving the venetian blind to one endposition, the tilt will be set to its corresponding endposition
4. When moving the blind to any other position, the tilt is not adjusted automatically
5. If the blind is in closed endposition (blind down) and the tilt is adjusted, the blind position will also be adjusted. This happens because the slat movement time is part of the calibrated movement time the blind needs to fully open or close. So if we adjust the tilt when the blind is in down-endposition, we are moving it a bit up.
![Bildschirmfoto 2022-07-11 um 15 10 58](https://user-images.githubusercontent.com/48414034/178271876-acf664bc-7563-40fb-aea1-c3b295dfd316.png)

At the moment I have an alpha-version for testing arround a bit. 

I tried to commit my changes to oliver´s repo to update the PR, but wasn´t successful. Maybe someone can help me out?

**Comment by ReToCode** [comment]
Until this is implemented and merged I've used a hacky shortcut to achieve something similar, might be helpful to someone:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/16611466/179972873-7b611c31-7fa7-4d45-89ad-c5656db8c582.png">

**Comment by MarcinVaadin** [comment]
@ReToCode how did you make it work? I'm ending up with: `{"code":404,"message":"No handler for Cover.Close"}`
