### ISSUE TITLE
Feature Request: Auto ON (+delay)

### ISSUE THREAD

**Issue by Mmmike82** [mongoose-os-apps/shelly-homekit#811]
Hello,

I'm a real fan of your work! Thanks for all the effort you put in so far. I love how they work with homekit!
To be honest, I'm only one thing missing: AUTO ON and AUTO ON Delay. 
It should be exactly the same as AUTO OFF and AUTO OFF Delay but then for turning it on.

In the native Shelly app this is an option with the Shelly Plug S as far I know. I use it all the time to reset devices such as my wifi router. When I shut down the router with the Shelly, of course the shelly loses wifi connection and I can't turn it on again by the homekit app. Therefore I need it to power on again automatically.

Could you please, please, please add this?

Thank you so much in advance!

Greetings from the Netherlands,

Mike

**Comment by timoschilling** [comment]
> but still no possibility to use AUTO ON and AUTO OFF simultaneously

Whats your use case for both? In you first post you didn't show one up. If you need the auto off to restart the router once a day, you can use homekit to turn it off and the inverted auto of to turn it back on.

>  in my opinion is the most logical thing to do is to code AUTO ON

yes it is, but that doesn't mean that we need every feature just because it's simple. Many simple things also give complex code.

As I see that you are new here, maybe you should keep in mind that this is a free open source software. We pick up ideas if we like it, we didn't get any money from someone for our work here. 

> Are you the only one who judges if my request is fair?

No

**Comment by Mmmike82** [comment]
Timo, don't get me wrong, I love what you guys are doing and appreciate your time and effort to answer my questions and I'm not saying you're doing are saying anything wrong. I didn't want to push anything. I'm sorry if it come across this way.
I just wanted to give my point of view on this matter,.. from another perspective. Now I have more background information from you and andyblac, I can understand your point of view. Now your workaround seems more logical to me and I will use it like u mentioned. Thanks for your time guys.

**Comment by dimovstanimir** [comment]
Hi Guys,
is there any updates on this as I also really need this delayed Auto ON feature because my router needs reboot once or twice a week. I have a raspberry pi that I want to connect to it and monitor the routers behaviour and when it detects that it needs reboot it will simply send auto off + 10 seconds delayed Auto ON signal so the router will lose power and shutdown and will get power after 10 seconds and voala it will be rebooted. Please excuse me if this feature was already implemented it is just I need to be sure before buying some of these devices. Thanks in advance for your time guys and wish you all the best! :)
