### ISSUE TITLE
Problems with RGBW light strip colors

### ISSUE THREAD

**Issue by Kai120517** [mongoose-os-apps/shelly-homekit#857]
Hi, I have the Shelly RGBW2 (flashed with HomeKit) connected to a high quality RGBW light strip that I bought, but the problem is that when I try to set a color that is made from only the rgb section, it also turns on the white led. That creates a whole different color that I didn’t want.
Is there a way to fix it? I need it to not send a signal to turn white on.
Thanks in advance

**Comment by timoschilling** [comment]
Can you please a picture from the strip, the wiring on the Shelly side and of the web UI please

**Comment by Kai120517** [comment]
![3A5B8CBA-DF65-4AEE-ADD1-96BB177F958E](https://user-images.githubusercontent.com/95568731/145039446-c6285afb-dddd-4bcf-8979-42c776119a1c.jpeg)
![F6A9114C-FBB9-4418-9B6C-0C21BE5F1BD1](https://user-images.githubusercontent.com/95568731/145039478-a34a8180-11f5-482c-9cf8-583f3ecf7130.png)
![4F5C7083-C932-4ED3-99E6-0D489EF38459](https://user-images.githubusercontent.com/95568731/145039489-92f3e145-9001-4eb6-9fa1-47f7ea80ec13.jpeg)

**Comment by timoschilling** [comment]
I tested it with my and it is expected behaviour.

Let me explain: Hue 151, means 100% blue and 52% green, which is mathematically a light green. But the Problem is that a blue LED has a higher intensity then a green one, that's results in a more blue colour.

From my point of view the problem is that your LED strip isn't good (must strips have that problem).

> it also turns on the white led

The my logs are showing that only blue and green are on. So if you directly look on your strip and you really see the white LED on, there is a issue with your Shelly, your strip or the wiring.
