### ISSUE TITLE
Shelly 1 do Not work with Motion Sensor

### ISSUE THREAD

**Issue by DannySmithKovi** [mongoose-os-apps/shelly-homekit#916]
Hi, first of all sorry for my bad english. 
Since this morning all of shelly 1 do not work anymore with my motion sensors from hue. Since yesterday they worked great. Yesterday evening i installed ios15.3.
They work, when I put it on or off in HomeKit manually. But not automatically over motion Sensors from hue. Also the hue button does not work.

**Comment by timoschilling** [comment]
If you can control the Shelly from the Home app, the problem isn't on our side. Because our system didn't have any knowledge about automatisation, they are only handled internally in HomeKit on your iDevices. Maybe iOS15.3 has bricked your automatisation or you HomeHub has a problem or you need to update all your devices to 15.3.
