### ISSUE TITLE
Shelly Plug S - Initial State Off: Outlet is ON for about two seconds before being turned off

### ISSUE THREAD

**Issue by eilersKevin** [mongoose-os-apps/shelly-homekit#993]
In the mode 'Initial State Off' the outlet has power for about two seconds after a reboot before it is turned off again.
This does not happen with the stock firmware.

**Comment by eilersKevin** [comment]
I do not, but I just enabled one, to see whether it makes a difference. Unfortunately it did not. 

It seems that the relay is switched on as soon as there is power, and that it then takes 2-4 seconds to reach line 227 in shelly_switch.cpp where it is disabled again. You can clearly hear the click of the relais right after providing power.
This click does not happen with the stock firmware, so it seems that the decision to switch it on or off is taken much earlier there.

**Comment by eilersKevin** [comment]
I also tried to play around with the 'Invert Output' option, to maybe trick it into a different behavior, but to no avail.

**Comment by timoschilling** [comment]
Can you please post a screen shot of your switch settings and which version are you currently using?

**Comment by eilersKevin** [comment]
<img width="368" alt="ShellyPlugS_1" src="https://user-images.githubusercontent.com/2461770/169481509-b0e3f247-0f74-4497-87cc-f953f3976cd5.png">
<img width="367" alt="ShellyPlugS_2" src="https://user-images.githubusercontent.com/2461770/169481527-1a8a903e-66cf-41ea-8ba5-da10ab9823f5.png">

Version: 2.10.1
Build: 20211016-123215/2.10.1-gc8923b3-master 

Homekit is currently disabled but enabling it, does not change the behaviour.

**Comment by rojer** [comment]
repro'd this. it's... weird. not sure what sets GPIO15, but something does. i'll have a closer look later.

**Comment by rojer** [comment]
a pretty interesting bug, see https://github.com/cesanta/mongoose-os/commit/43e90e0cf30d3b2c9b53f75d79c12e56f7d45b17 for description.

the reason it does not happen in stock fw is that they probably configure GPIO15 (relay) first, then GPIO13 (button), or do it in quick succession such that it's not noticeable.
in our case we have the pause to enter failsafe mode that only configures the button to read its status but due to this bug also drives the relay to on.

thanks for reporting, this will be in the next release.

**Comment by eilersKevin** [comment]
Thanks for fixig this so quickly, looking forward to the next release.
